# Generated by Django 5.2 on 2025-05-09 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_feedback_options'),
        ('core', '0005_alter_feedback_options_feedback_read'),
    ]

    operations = [
    ]
