# Generated by Django 5.2 on 2025-05-09 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20250509_1750'),
        ('core', '0006_merge_20250509_1837'),
    ]

    operations = [
    ]
